name: Terraform

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform-plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
        run: terraform init

      - name: Terraform Plan
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
        run: terraform plan

  terraform-apply:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
        run: terraform init

      - name: Terraform Plan
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
        run: terraform apply -auto-approve tfplan